import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { startsWithSvgRoot } from "../../src/execution/kroki/svg-header.js";

describe("startsWithSvgRoot", () => {
  it("accepts bare roots and the prologs real Kroki renderers emit", () => {
    for (const header of [
      '<svg xmlns="http://www.w3.org/2000/svg">',
      "\uFEFF  <SVG>",
      '<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n<svg\n  width="10">',
      [
        '<?xml version="1.0" encoding="UTF-8" standalone="no"?>',
        '<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">',
        "<!-- Generated by graphviz -->",
        "<!-- Title: G Pages: 1 -->",
        '<svg width="62pt">',
      ].join("\n"),
    ]) {
      assert.equal(startsWithSvgRoot(header), true, header);
    }
  });

  it("rejects non-SVG roots and unterminated prolog parts", () => {
    for (const header of [
      "",
      "not svg",
      "<html><svg>",
      "<svgfoo>",
      "<?xml version='1.0'",
      "<!-- never closed <svg>",
      "<!DOCTYPE html><svg>",
      "<!DOCTYPE svg",
    ]) {
      assert.equal(startsWithSvgRoot(header), false, header);
    }
  });

  it("stays fast on adversarial repeated comments", () => {
    const header = `<!--${"--><!--".repeat(50_000)}`;
    const started = performance.now();
    assert.equal(startsWithSvgRoot(header), false);
    assert.ok(performance.now() - started < 1_000);
  });
});
