import {
  filesystemDirectoryQuerySchema,
  filesystemDirectoryResponseSchema,
  filesystemProjectEntriesQuerySchema,
  filesystemProjectEntriesResponseSchema,
  filesystemProjectMonitorClearRequestSchema,
  filesystemProjectMonitorStateSchema,
  filesystemProjectMonitorSyncRequestSchema,
  filesystemProjectRefreshRequestSchema,
  monitorRefreshResponseSchema,
  filesystemProjectEntryCreateRequestSchema,
  filesystemProjectEntryCreateResponseSchema,
} from "./filesystem.js";
import { defineOperation } from "../../operations/definition.js";

export const filesystemOperationDefinitions = [
  defineOperation(
    "filesystem.directories.list",
    filesystemDirectoryQuerySchema.optional(),
    filesystemDirectoryResponseSchema,
    "read",
    "none",
    ["workbench_server"] as const,
    "operation.filesystem.directories.list",
  ),
  defineOperation(
    "filesystem.project.entries.list",
    filesystemProjectEntriesQuerySchema,
    filesystemProjectEntriesResponseSchema,
    "read",
    "none",
    ["workbench_server"] as const,
    "operation.filesystem.project.entries.list",
  ),
  defineOperation(
    "filesystem.project.monitor.sync",
    filesystemProjectMonitorSyncRequestSchema,
    filesystemProjectMonitorStateSchema,
    "read",
    "none",
    ["workbench_server"] as const,
    "operation.filesystem.project.monitor.sync",
  ),
  defineOperation(
    "filesystem.project.monitor.clear",
    filesystemProjectMonitorClearRequestSchema,
    filesystemProjectMonitorStateSchema,
    "read",
    "none",
    ["workbench_server"] as const,
    "operation.filesystem.project.monitor.clear",
  ),
  defineOperation(
    "filesystem.project.refresh",
    filesystemProjectRefreshRequestSchema,
    monitorRefreshResponseSchema,
    "read",
    "none",
    ["workbench_server"] as const,
    "operation.filesystem.project.refresh",
  ),
  defineOperation(
    "filesystem.project.entries.create",
    filesystemProjectEntryCreateRequestSchema,
    filesystemProjectEntryCreateResponseSchema,
    "mutation",
    "recommended",
    ["workbench_server"] as const,
    "operation.filesystem.project.entries.create",
  ),
] as const;
