export const unifiedTimelineInvariantCoverage = [
  ["INV-AUTH-01", 2, "single authority and mutation inventory"],
  ["INV-ID-01", 1, "identity, ancestry, and ordering"],
  ["INV-HEAD-01", 2, "head ownership and selection fences"],
  ["INV-COMMIT-01", 2, "atomic transition failure injection"],
  ["INV-RECEIPT-01", 2, "durable semantic command replay"],
  ["INV-OUTCOME-01", 7, "typed producer and consumer outcomes"],
  ["INV-CHECKPOINT-01", 4, "canonical checkpoint applicability"],
  ["INV-BARRIER-01", 4, "wait-group state and continuation"],
  ["INV-AGENT-01", 4, "independent child lifecycle"],
  ["INV-EFFECT-01", 5, "tool replay capability and effect identity"],
  ["INV-CLAIM-01", 5, "attempt claim fencing"],
  ["INV-RECOVERY-01", 5, "evidence-bearing recovery actions"],
  ["INV-PROVIDER-01", 5, "durable provider phases"],
  ["INV-ARTIFACT-01", 5, "artifact preparation and retention"],
  ["INV-VIEW-01", 7, "projection watermarks and rebuild"],
  ["INV-PAGE-01", 7, "fixed-view pagination"],
  ["INV-CONTEXT-01", 3, "branch-safe context boundaries"],
  ["INV-DELIVERY-01", 7, "at-least-once delivery reconciliation"],
  ["INV-POLICY-01", 6, "file authority and fresh evaluation"],
  ["INV-POLICY-02", 6, "invalid overlay recovery"],
  ["INV-POLICY-03", 6, "invalid rule-set fallback"],
  ["INV-POLICY-04", 6, "remembered-save partial outcomes"],
  ["INV-BACKUP-01", 8, "complete portable backup"],
  ["INV-DELETE-01", 8, "deletion finalization and replay evidence"],
  ["INV-RESTORE-01", 8, "restore incarnation fencing"],
  ["INV-MIGRATE-01", 9, "new-only restart-safe migration"],
  ["INV-MIGRATE-02", 9, "source authority proof fixtures"],
  ["INV-PERF-01", 10, "boundedness and latency smoke"],
  ["INV-COVERAGE-01", 10, "coverage manifest audit"],
] as const;

export type UnifiedTimelineInvariantId =
  (typeof unifiedTimelineInvariantCoverage)[number][0];

export const unifiedTimelineMutationInventory = [
  ["conversation_create_or_import", "history_imported"],
  ["accepted_user_input_and_run_start", "entries_appended"],
  ["assistant_response_and_tool_proposals", "entries_appended"],
  ["tool_result_attachment", "entries_appended"],
  ["child_result_attachment", "entries_appended"],
  ["human_answer_approval_or_review", "interaction_changed"],
  ["cross_conversation_plan_acceptance", "interaction_changed"],
  ["navigation", "selection_changed"],
  ["summary_or_context_recipe", "context_boundary_committed"],
  ["run_lifecycle", "run_changed"],
  ["policy_authorization_or_claim", "execution_changed"],
  ["remembered_policy_save", "policy_save_intent"],
  ["recovery_or_abandonment", "execution_changed"],
  ["deletion", "deletion_intent"],
  ["stream_progress_heartbeat_or_log", "non_history"],
  ["queued_input_during_active_run", "non_history"],
] as const;
