import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const packageDir = join(scriptDir, "..");
const assetsDir = join(packageDir, "assets");
const outputDir = join(packageDir, "build");
const iconsDir = join(outputDir, "icons");
const trayDir = join(outputDir, "tray");

const appIconSizes = [16, 24, 32, 48, 64, 128, 256, 512, 1024];
const trayIconSizes = [16, 24, 32];

await rm(outputDir, { recursive: true, force: true });
await mkdir(iconsDir, { recursive: true });
await mkdir(trayDir, { recursive: true });

const appIconSvg = await readFile(join(assetsDir, "app-icon.svg"));
const trayIconSvg = await readFile(join(assetsDir, "tray-icon.svg"), "utf8");

await Promise.all(
  appIconSizes.map(async (size) => {
    await sharp(appIconSvg)
      .resize(size, size, { fit: "contain" })
      .png({ compressionLevel: 9 })
      .toFile(join(iconsDir, `${size}x${size}.png`));
  }),
);

await writeTrayVariant("tray-light", "#111827");
await writeTrayVariant("tray-dark", "#F8FAFC");
await writeTrayVariant("tray-template", "#000000");

async function writeTrayVariant(name, color) {
  const svg = Buffer.from(trayIconSvg.replaceAll("currentColor", color));
  await Promise.all(
    trayIconSizes.map(async (size) => {
      const filename = size === 32 ? `${name}.png` : `${name}-${size}.png`;
      await sharp(svg)
        .resize(size, size, { fit: "contain" })
        .png({ compressionLevel: 9 })
        .toFile(join(trayDir, filename));
    }),
  );
}

await writeFile(
  join(outputDir, "README.md"),
  "Generated by scripts/generate-icons.mjs from assets/*.svg. Do not edit generated PNGs by hand.\n",
);
