import type { ToolName, ToolRisk } from "@nervekit/shared";

const toolRisks: Record<ToolName, ToolRisk> = {
  read: "read",
  bash: "command",
  python: "command",
  edit: "workspace_write",
  write: "workspace_write",
  grep: "read",
  find: "read",
  ls: "read",
  ask_user: "interaction",
  todos_set: "interaction",
  todos_get: "read",
  web_search: "network",
  web_fetch: "network",
  jira_search_users: "network",
  jira_search_issues: "network",
  jira_get_issue: "network",
  jira_get_project: "network",
  jira_create_issue: "command",
  jira_update_issue: "command",
  jira_add_comment: "command",
  jira_transition_issue: "command",
  confluence_search_spaces: "network",
  confluence_search_pages: "network",
  confluence_get_page: "network",
  confluence_download_pages: "network",
  confluence_create_page: "command",
  confluence_update_page: "command",
  confluence_publish_pages: "command",
  confluence_upload_attachment: "command",
  task_start: "command",
  task_status: "read",
  task_logs: "read",
  task_cancel: "command",
  task_restart: "command",
  task_list: "read",
  explore: "agent_spawn",
  plan_mode_enter: "interaction",
  plan_mode_present: "interaction",
  plan_mode_force_exit: "interaction",
};

export function coreToolRiskForName(name: ToolName): ToolRisk {
  return toolRisks[name] ?? "command";
}
